### ISSUE TITLE
CDN issue

### ISSUE THREAD

**Issue by hrstoyanov** [gnat/surreal#36]
How can I download a particular version?

for example version 1.2.1 does not download from this:
```https://cdn.jsdelivr.net/gh/gnat/surreal@1.2.1/surreal.js```

Also, can you, please, offer a minified version (no comments inside,  at least)?

Also, can you, please, do the same for you other awesome project [css-scope-inline](https://github.com/gnat/css-scope-inline)

**Comment by gnat** [comment]
People are welcome to do as they please in their own private workflows, but minified / obfuscated releases are not currently planned because promoting "builds" would put major inadvertent pressure on developers to use them.

This sucks because it removes the debuggable, simple, open, auditable nature of surreal and leads down the path to source maps, dependencies, and other DX friction. The upside is minimal, particularly if the server has gzip or zstd enabled.
